
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_FAILURE = 'SEND_PASSWORD_RESET_FAILURE';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const TENANT_LIST_REQUEST = 'TENANT_LIST_REQUEST';
export const TENANT_LIST_FAILURE = 'TENANT_LIST_FAILURE';
export const TENANT_LIST_SUCCESS = 'TENANT_LIST_SUCCESS';

export const TENANT_DETAIL_REQUEST = 'TENANT_DETAIL_REQUEST';
export const TENANT_DETAIL_FAILURE = 'TENANT_DETAIL_FAILURE';
export const TENANT_DETAIL_SUCCESS = 'TENANT_DETAIL_SUCCESS';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';

export const NAVIGATION_REQUEST = 'NAVIGATION_REQUEST';
export const NAVIGATION_FAILURE = 'NAVIGATION_FAILURE';
export const NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS';

export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const CLIENT_LIST_FAILURE = 'CLIENT_LIST_FAILURE';
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS';

export const CLIENT_DETAIL_REQUEST = 'CLIENT_DETAIL_REQUEST';
export const CLIENT_DETAIL_FAILURE = 'CLIENT_DETAIL_FAILURE';
export const CLIENT_DETAIL_SUCCESS = 'CLIENT_DETAIL_SUCCESS';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';

export const ASSOCIATE_LIST_REQUEST = 'ASSOCIATE_LIST_REQUEST';
export const ASSOCIATE_LIST_FAILURE = 'ASSOCIATE_LIST_FAILURE';
export const ASSOCIATE_LIST_SUCCESS = 'ASSOCIATE_LIST_SUCCESS';

export const ASSOCIATE_DETAIL_REQUEST = 'ASSOCIATE_DETAIL_REQUEST';
export const ASSOCIATE_DETAIL_FAILURE = 'ASSOCIATE_DETAIL_FAILURE';
export const ASSOCIATE_DETAIL_SUCCESS = 'ASSOCIATE_DETAIL_SUCCESS';

export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_FAILURE = 'TASK_LIST_FAILURE';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';

export const TASK_DETAIL_REQUEST = 'TASK_DETAIL_REQUEST';
export const TASK_DETAIL_FAILURE = 'TASK_DETAIL_FAILURE';
export const TASK_DETAIL_SUCCESS = 'TASK_DETAIL_SUCCESS';

export const STAFF_LIST_REQUEST = 'STAFF_LIST_REQUEST';
export const STAFF_LIST_FAILURE = 'STAFF_LIST_FAILURE';
export const STAFF_LIST_SUCCESS = 'STAFF_LIST_SUCCESS';

export const STAFF_DETAIL_REQUEST = 'STAFF_DETAIL_REQUEST';
export const STAFF_DETAIL_FAILURE = 'STAFF_DETAIL_FAILURE';
export const STAFF_DETAIL_SUCCESS = 'STAFF_DETAIL_SUCCESS';

export const FINANCIAL_LIST_REQUEST = 'FINANCIAL_LIST_REQUEST';
export const FINANCIAL_LIST_FAILURE = 'FINANCIAL_LIST_FAILURE';
export const FINANCIAL_LIST_SUCCESS = 'FINANCIAL_LIST_SUCCESS';

export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_FAILURE = 'TAG_LIST_FAILURE';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';

export const TAG_DETAIL_REQUEST = 'TAG_DETAIL_REQUEST';
export const TAG_DETAIL_FAILURE = 'TAG_DETAIL_FAILURE';
export const TAG_DETAIL_SUCCESS = 'TAG_DETAIL_SUCCESS';

export const HOW_HEAR_LIST_REQUEST = 'HOW_HEAR_LIST_REQUEST';
export const HOW_HEAR_LIST_FAILURE = 'HOW_HEAR_LIST_FAILURE';
export const HOW_HEAR_LIST_SUCCESS = 'HOW_HEAR_LIST_SUCCESS';

export const HOW_HEAR_DETAIL_REQUEST = 'HOW_HEAR_DETAIL_REQUEST';
export const HOW_HEAR_DETAIL_FAILURE = 'HOW_HEAR_DETAIL_FAILURE';
export const HOW_HEAR_DETAIL_SUCCESS = 'HOW_HEAR_DETAIL_SUCCESS';

export const AWAY_LOG_LIST_REQUEST = 'AWAY_LOG_LIST_REQUEST';
export const AWAY_LOG_LIST_FAILURE = 'AWAY_LOG_LIST_FAILURE';
export const AWAY_LOG_LIST_SUCCESS = 'AWAY_LOG_LIST_SUCCESS';

export const AWAY_LOG_DETAIL_REQUEST = 'AWAY_LOG_DETAIL_REQUEST';
export const AWAY_LOG_DETAIL_FAILURE = 'AWAY_LOG_DETAIL_FAILURE';
export const AWAY_LOG_DETAIL_SUCCESS = 'AWAY_LOG_DETAIL_SUCCESS';

export const BULLETIN_BOARD_ITEM_LIST_REQUEST = 'BULLETIN_BOARD_ITEM_LIST_REQUEST';
export const BULLETIN_BOARD_ITEM_LIST_FAILURE = 'BULLETIN_BOARD_ITEM_LIST_FAILURE';
export const BULLETIN_BOARD_ITEM_LIST_SUCCESS = 'BULLETIN_BOARD_ITEM_LIST_SUCCESS';

export const BULLETIN_BOARD_ITEM_DETAIL_REQUEST = 'BULLETIN_BOARD_ITEM_DETAIL_REQUEST';
export const BULLETIN_BOARD_ITEM_DETAIL_FAILURE = 'BULLETIN_BOARD_ITEM_DETAIL_FAILURE';
export const BULLETIN_BOARD_ITEM_DETAIL_SUCCESS = 'BULLETIN_BOARD_ITEM_DETAIL_SUCCESS';

export const SKILL_SET_LIST_REQUEST = 'SKILL_SET_LIST_REQUEST';
export const SKILL_SET_LIST_FAILURE = 'SKILL_SET_LIST_FAILURE';
export const SKILL_SET_LIST_SUCCESS = 'SKILL_SET_LIST_SUCCESS';

export const SKILL_SET_DETAIL_REQUEST = 'SKILL_SET_DETAIL_REQUEST';
export const SKILL_SET_DETAIL_FAILURE = 'SKILL_SET_DETAIL_FAILURE';
export const SKILL_SET_DETAIL_SUCCESS = 'SKILL_SET_DETAIL_SUCCESS';

export const INSURANCE_REQUIREMENT_LIST_REQUEST = 'INSURANCE_REQUIREMENT_LIST_REQUEST';
export const INSURANCE_REQUIREMENT_LIST_FAILURE = 'INSURANCE_REQUIREMENT_LIST_FAILURE';
export const INSURANCE_REQUIREMENT_LIST_SUCCESS = 'INSURANCE_REQUIREMENT_LIST_SUCCESS';

export const INSURANCE_REQUIREMENT_DETAIL_REQUEST = 'INSURANCE_REQUIREMENT_DETAIL_REQUEST';
export const INSURANCE_REQUIREMENT_DETAIL_FAILURE = 'INSURANCE_REQUIREMENT_DETAIL_FAILURE';
export const INSURANCE_REQUIREMENT_DETAIL_SUCCESS = 'INSURANCE_REQUIREMENT_DETAIL_SUCCESS';

export const SERVICE_FEE_LIST_REQUEST = 'SERVICE_FEE_LIST_REQUEST';
export const SERVICE_FEE_LIST_FAILURE = 'SERVICE_FEE_LIST_FAILURE';
export const SERVICE_FEE_LIST_SUCCESS = 'SERVICE_FEE_LIST_SUCCESS';

export const SERVICE_FEE_DETAIL_REQUEST = 'SERVICE_FEE_DETAIL_REQUEST';
export const SERVICE_FEE_DETAIL_FAILURE = 'SERVICE_FEE_DETAIL_FAILURE';
export const SERVICE_FEE_DETAIL_SUCCESS = 'SERVICE_FEE_DETAIL_SUCCESS';

export const ARCHIVED_CLIENT_LIST_REQUEST = 'ARCHIVED_CLIENT_LIST_REQUEST';
export const ARCHIVED_CLIENT_LIST_FAILURE = 'ARCHIVED_CLIENT_LIST_FAILURE';
export const ARCHIVED_CLIENT_LIST_SUCCESS = 'ARCHIVED_CLIENT_LIST_SUCCESS';

export const ARCHIVED_CLIENT_DETAIL_REQUEST = 'ARCHIVED_CLIENT_DETAIL_REQUEST';
export const ARCHIVED_CLIENT_DETAIL_FAILURE = 'ARCHIVED_CLIENT_DETAIL_FAILURE';
export const ARCHIVED_CLIENT_DETAIL_SUCCESS = 'ARCHIVED_CLIENT_DETAIL_SUCCESS';

export const VEHICLE_TYPE_LIST_REQUEST = 'VEHICLE_TYPE_LIST_REQUEST';
export const VEHICLE_TYPE_LIST_FAILURE = 'VEHICLE_TYPE_LIST_FAILURE';
export const VEHICLE_TYPE_LIST_SUCCESS = 'VEHICLE_TYPE_LIST_SUCCESS';

export const VEHICLE_TYPE_DETAIL_REQUEST = 'VEHICLE_TYPE_DETAIL_REQUEST';
export const VEHICLE_TYPE_DETAIL_FAILURE = 'VEHICLE_TYPE_DETAIL_FAILURE';
export const VEHICLE_TYPE_DETAIL_SUCCESS = 'VEHICLE_TYPE_DETAIL_SUCCESS';

export const PARTNER_LIST_REQUEST = 'PARTNER_LIST_REQUEST';
export const PARTNER_LIST_FAILURE = 'PARTNER_LIST_FAILURE';
export const PARTNER_LIST_SUCCESS = 'PARTNER_LIST_SUCCESS';

export const PARTNER_DETAIL_REQUEST = 'PARTNER_DETAIL_REQUEST';
export const PARTNER_DETAIL_FAILURE = 'PARTNER_DETAIL_FAILURE';
export const PARTNER_DETAIL_SUCCESS = 'PARTNER_DETAIL_SUCCESS';

export const STAFF_COMMENT_LIST_REQUEST = 'STAFF_COMMENT_LIST_REQUEST';
export const STAFF_COMMENT_LIST_FAILURE = 'STAFF_COMMENT_LIST_FAILURE';
export const STAFF_COMMENT_LIST_SUCCESS = 'STAFF_COMMENT_LIST_SUCCESS';

export const CLIENT_COMMENT_LIST_REQUEST = 'CLIENT_COMMENT_LIST_REQUEST';
export const CLIENT_COMMENT_LIST_FAILURE = 'CLIENT_COMMENT_LIST_FAILURE';
export const CLIENT_COMMENT_LIST_SUCCESS = 'CLIENT_COMMENT_LIST_SUCCESS';

export const ASSOCIATE_COMMENT_LIST_REQUEST = 'ASSOCIATE_COMMENT_LIST_REQUEST';
export const ASSOCIATE_COMMENT_LIST_FAILURE = 'ASSOCIATE_COMMENT_LIST_FAILURE';
export const ASSOCIATE_COMMENT_LIST_SUCCESS = 'ASSOCIATE_COMMENT_LIST_SUCCESS';

export const ACTIVITY_SHEET_LIST_REQUEST = 'ACTIVITY_SHEET_LIST_REQUEST';
export const ACTIVITY_SHEET_LIST_FAILURE = 'ACTIVITY_SHEET_LIST_FAILURE';
export const ACTIVITY_SHEET_LIST_SUCCESS = 'ACTIVITY_SHEET_LIST_SUCCESS';

export const ACTIVITY_SHEET_DETAIL_REQUEST = 'ACTIVITY_SHEET_DETAIL_REQUEST';
export const ACTIVITY_SHEET_DETAIL_FAILURE = 'ACTIVITY_SHEET_DETAIL_FAILURE';
export const ACTIVITY_SHEET_DETAIL_SUCCESS = 'ACTIVITY_SHEET_DETAIL_SUCCESS';

export const ORDER_COMMENT_LIST_REQUEST = 'ORDER_COMMENT_LIST_REQUEST';
export const ORDER_COMMENT_LIST_FAILURE = 'ORDER_COMMENT_LIST_FAILURE';
export const ORDER_COMMENT_LIST_SUCCESS = 'ORDER_COMMENT_LIST_SUCCESS';

export const PARTNER_COMMENT_LIST_REQUEST = 'PARTNER_COMMENT_LIST_REQUEST';
export const PARTNER_COMMENT_LIST_FAILURE = 'PARTNER_COMMENT_LIST_FAILURE';
export const PARTNER_COMMENT_LIST_SUCCESS = 'PARTNER_COMMENT_LIST_SUCCESS';

export const ONGOING_ORDER_LIST_REQUEST = 'ONGOING_ORDER_LIST_REQUEST';
export const ONGOING_ORDER_LIST_FAILURE = 'ONGOING_ORDER_LIST_FAILURE';
export const ONGOING_ORDER_LIST_SUCCESS = 'ONGOING_ORDER_LIST_SUCCESS';

export const ONGOING_ORDER_DETAIL_REQUEST = 'ONGOING_ORDER_DETAIL_REQUEST';
export const ONGOING_ORDER_DETAIL_FAILURE = 'ONGOING_ORDER_DETAIL_FAILURE';
export const ONGOING_ORDER_DETAIL_SUCCESS = 'ONGOING_ORDER_DETAIL_SUCCESS';

export const ONGOING_ORDER_COMMENT_LIST_REQUEST = 'ONGOING_ORDER_COMMENT_LIST_REQUEST';
export const ONGOING_ORDER_COMMENT_LIST_FAILURE = 'ONGOING_ORDER_COMMENT_LIST_FAILURE';
export const ONGOING_ORDER_COMMENT_LIST_SUCCESS = 'ONGOING_ORDER_COMMENT_LIST_SUCCESS';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';

export const CLIENT_FILE_LIST_REQUEST = 'CLIENT_FILE_LIST_REQUEST';
export const CLIENT_FILE_LIST_FAILURE = 'CLIENT_FILE_LIST_FAILURE';
export const CLIENT_FILE_LIST_SUCCESS = 'CLIENT_FILE_LIST_SUCCESS';

export const ASSOCIATE_FILE_LIST_REQUEST = 'ASSOCIATE_FILE_LIST_REQUEST';
export const ASSOCIATE_FILE_LIST_FAILURE = 'ASSOCIATE_FILE_LIST_FAILURE';
export const ASSOCIATE_FILE_LIST_SUCCESS = 'ASSOCIATE_FILE_LIST_SUCCESS';

export const ORDER_FILE_LIST_REQUEST = 'ORDER_FILE_LIST_REQUEST';
export const ORDER_FILE_LIST_FAILURE = 'ORDER_FILE_LIST_FAILURE';
export const ORDER_FILE_LIST_SUCCESS = 'ORDER_FILE_LIST_SUCCESS';

export const STAFF_FILE_LIST_REQUEST = 'STAFF_FILE_LIST_REQUEST';
export const STAFF_FILE_LIST_FAILURE = 'STAFF_FILE_LIST_FAILURE';
export const STAFF_FILE_LIST_SUCCESS = 'STAFF_FILE_LIST_SUCCESS';

export const PARTNER_FILE_LIST_REQUEST = 'PARTNER_FILE_LIST_REQUEST';
export const PARTNER_FILE_LIST_FAILURE = 'PARTNER_FILE_LIST_FAILURE';
export const PARTNER_FILE_LIST_SUCCESS = 'PARTNER_FILE_LIST_SUCCESS';

export const DEPOSIT_LIST_REQUEST = 'DEPOSIT_LIST_REQUEST';
export const DEPOSIT_LIST_FAILURE = 'DEPOSIT_LIST_FAILURE';
export const DEPOSIT_LIST_SUCCESS = 'DEPOSIT_LIST_SUCCESS';

export const DEPOSIT_DETAIL_REQUEST = 'DEPOSIT_DETAIL_REQUEST';
export const DEPOSIT_DETAIL_FAILURE = 'DEPOSIT_DETAIL_FAILURE';
export const DEPOSIT_DETAIL_SUCCESS = 'DEPOSIT_DETAIL_SUCCESS';

export const UNIFIED_SEARCH_ITEM_LIST_REQUEST = 'UNIFIED_SEARCH_ITEM_LIST_REQUEST';
export const UNIFIED_SEARCH_ITEM_LIST_FAILURE = 'UNIFIED_SEARCH_ITEM_LIST_FAILURE';
export const UNIFIED_SEARCH_ITEM_LIST_SUCCESS = 'UNIFIED_SEARCH_ITEM_LIST_SUCCESS';
